name: Scrape Motorcycle Classes

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install puppeteer node-fetch

    - name: Setup Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        npx puppeteer browsers install chrome

    - name: Run scraper
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
      run: node scraper.js

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: motorcycle-classes-${{ github.run_number }}
        path: '*.json'
        retention-days: 30

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --exit-code; then
          git commit -m "Update motorcycle classes data $(date)"
          git push
        fi
